apiVersion: v1
kind: Secret
metadata:
  name: jfrogcreds
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0cmlhbHI0NzF4ZC5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiWkc5amEyVnlZM0psWkhNNlNtWnliMmRqY21Wa2N6RXlNdz09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson